services:
  #App (React - Frontend)
  reac:
    container_name: reac_base
    # image: reac:1.0.0
    build: "./frontend-rh"
    environment:
      - BACKEND_URL=http://springboot:8080
    ports:
      - 3000:3000
      - 80:80
    depends_on:
      - springboot

  #App (Springboot - Backend)
  springboot:
    container_name: springboot_base
    # image: springboot:1.0.0
    build: "./backend-rh"
    # ports:
    #   - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/tryapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
      # - SPRING_DB_HOST=postgres_db
      # - SPRING_DB_PORT=5432
      # - SPRING_DB_NAME=tryapi
      # - SPRING_DB_USER=postgres
      # - SPRING_DB_PASSWORD=123456
    depends_on:
      - postgres_db

  #App (Postgres - Data Base)
  postgres_db:
    container_name: postgres_db_base
    image: postgres:12
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tryapi