services:
  reac:
    container_name: reac
    build: "./frontend-rh"
    ports:
      - 3000:3000
      - 80:80
    environment:
      - "BACKEND_URL=http://springboot:8080"
    depends_on:
      - springboot
    networks:
      - fad

  springboot:
    container_name: springboot
    build: "./backend-rh"
    ports:
      - 8080:8080
    environment:
      # - DATABASE_URL=jdbc:postgresql://postgres_db:5432/tryapi
      # - DATABASE_USERNAME=postgres
      # - DATABASE_PASSWORD=123456
      - "SPRING_DB_HOST=postgres_db"
      - "SPRING_DB_PORT=5432"
      - "SPRING_DB_NAME=tryapi"
      - "SPRING_DB_USER=postgres"
      - "SPRING_DB_PASSWORD=123456"
    depends_on:
      - postgres_db
    networks:
      - fad

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tryapi
    networks:
      - fad

networks:
  fad: