#for dev
FROM node:16-alpine as frontend

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# CMD ls
# CMD ["npm", "start"]
# CMD ["/bin/sh", "-c", "ls && npm start"]

FROM nginx:stable-alpine as production-stage

# ENV BACKEND_URL="localhost"

COPY ./nginx/default.template.conf /etc/nginx/conf.d/prueba

COPY --from=frontend /app/build/ /usr/share/nginx/html

EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
# CMD ["npm", "run", "build"]

CMD ["/bin/sh", "-c", "envsubst '${BACKEND_URL}' < /etc/nginx/conf.d/prueba > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
# CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
